name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: echo preparing for build ...
        - name: Check OS
        run: uname -a
      - name: Check Active Directory
        run: pwd
      - name: Refreshing Package JSON
        run: npm ci
      - name: Delete the previous build ...
        run: rm -rf /dist
      - name: Building ...
        run: npm run build
