name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Prepare
      run: echo preparing for build ...
    - name: Building
      run: echo building ...
    